package com.lenovo.sharkchao.hospital.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lenovo.sharkchao.hospital.model.Comment;
import com.lenovo.sharkchao.hospital.model.Customer;
import com.lenovo.sharkchao.hospital.model.JoinProductsWithOrders;
import com.lenovo.sharkchao.hospital.model.News;
import com.lenovo.sharkchao.hospital.model.Order;
import com.lenovo.sharkchao.hospital.model.Picture;
import com.lenovo.sharkchao.hospital.model.Product;
import com.lenovo.sharkchao.hospital.model.User;

import com.lenovo.sharkchao.hospital.greendao.CommentDao;
import com.lenovo.sharkchao.hospital.greendao.CustomerDao;
import com.lenovo.sharkchao.hospital.greendao.JoinProductsWithOrdersDao;
import com.lenovo.sharkchao.hospital.greendao.NewsDao;
import com.lenovo.sharkchao.hospital.greendao.OrderDao;
import com.lenovo.sharkchao.hospital.greendao.PictureDao;
import com.lenovo.sharkchao.hospital.greendao.ProductDao;
import com.lenovo.sharkchao.hospital.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig joinProductsWithOrdersDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig pictureDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CommentDao commentDao;
    private final CustomerDao customerDao;
    private final JoinProductsWithOrdersDao joinProductsWithOrdersDao;
    private final NewsDao newsDao;
    private final OrderDao orderDao;
    private final PictureDao pictureDao;
    private final ProductDao productDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        joinProductsWithOrdersDaoConfig = daoConfigMap.get(JoinProductsWithOrdersDao.class).clone();
        joinProductsWithOrdersDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        commentDao = new CommentDao(commentDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        joinProductsWithOrdersDao = new JoinProductsWithOrdersDao(joinProductsWithOrdersDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Comment.class, commentDao);
        registerDao(Customer.class, customerDao);
        registerDao(JoinProductsWithOrders.class, joinProductsWithOrdersDao);
        registerDao(News.class, newsDao);
        registerDao(Order.class, orderDao);
        registerDao(Picture.class, pictureDao);
        registerDao(Product.class, productDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        commentDaoConfig.clearIdentityScope();
        customerDaoConfig.clearIdentityScope();
        joinProductsWithOrdersDaoConfig.clearIdentityScope();
        newsDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        pictureDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public JoinProductsWithOrdersDao getJoinProductsWithOrdersDao() {
        return joinProductsWithOrdersDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
